export { default as TrendingTech } from './TrendingTech'
export { default as Projects } from './Projects'
export { default as Ideas } from './Ideas'
export { default as Profile } from './Profile'
export { default as NotFound } from './NotFound'
